# Use the official Node.js 18.3.1 image as a base
FROM node:18

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json into the container
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of your application code
COPY . .

RUN npm run build


# Expose the port your app runs on
EXPOSE 3000

# Start the application
CMD ["npm", "run","start"]
